config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :users, except: [:index, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/delete' => 'users#delete', as: 'delete'
  get '/users/:id/confirm' => 'users#confirm', as: 'confirm'
  get '/users/:id/barters' => 'users#barter', as: 'barters'
  get '/users/:id/wants' => 'users#want', as: 'wants'
  get '/users/:id/bookmarks' => 'users#bookmark', as: 'bookmarks'
  get '/users/:id/rooms' => 'users#room', as: 'users_rooms'
  
  resources :bartered_items, except: [:destroy] do
   resource :bookmarks,only: [:create, :destroy]
   resources :bartered_item_comments, only: [:create, :destroy]
  end
  patch 'bartered_items/:id/delete' => 'bartered_items#delete', as: 'barter_delete'
  get 'search' => 'bartered_items#search'
  
  resources :wanted_items, except: [:index]
  
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  
  
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  
end

app/models/bartered_item.rb
class BarteredItem < ApplicationRecord
  
  validates :title, presence: true
  validates :explanation, presence: true
  validates :barter_way, presence: true
  validates :desired_place, presence: true
  
  has_many :bartered_item_images, dependent: :destroy
  has_many :bartered_item_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  belongs_to :user
  accepts_attachments_for :bartered_item_images, attachment: :image
  
  enum barter_way:{郵送のみ:0,手渡しのみ:1,郵送・手渡し両方可:2}
  enum desired_place:{
     郵送:0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
     }
  enum barter_status:{募集中:0, 取引終了:1}
  
  def bookmarked_by?(user)
    bookmarks.where(user_id:user).exists?
  end
  
  
  
end

app/controllers/bartered_items_controller.rb
class BarteredItemsController < ApplicationController
  
  def new
    @bartered_item = BarteredItem.new
  end
  
  def create
    @bartered_item = BarteredItem.new(bartered_item_params)
    @bartered_item.no1_wanted_item_id 
    if @bartered_item.save
      redirect_to bartered_item_path(@bartered_item.id)
    else
      render :new
    end
  end
  
  def show
    @bartered_item = BarteredItem.find(params[:id])
    
    if @bartered_item.is_deleted == true
      redirect_to root_path
    end
    
    @bartered_item_comment = BarteredItemComment.new
    no1_wanted_item = WantedItem.where(id: @bartered_item.no1_wanted_item_id)
    no2_wanted_item = WantedItem.where(id: @bartered_item.no2_wanted_item_id)
    no3_wanted_item = WantedItem.where(id: @bartered_item.no3_wanted_item_id)
    @wanted_items = no1_wanted_item + no2_wanted_item + no3_wanted_item
  
    @user = @bartered_item.user
    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user == current_user
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id
              @isRoom = true
              @roomID = cu.room_id
            end
          end
        end
        unless @isRoom
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end

  def edit
    @bartered_item = BarteredItem.find(params[:id])
    if @bartered_item.is_deleted == true
      redirect_to root_path
    end
  end
  
  def update
    @bartered_item = BarteredItem.find(params[:id])
    @bartered_item.update(bartered_item_params)
    redirect_to bartered_item_path(@bartered_item.id)
  end
  
  def delete
    @bartered_item = BarteredItem.find(params[:id])
    @bartered_item.update(is_deleted: true)
    redirect_to barters_path(current_user)
  end
  
  def index
    @bartered_items = BarteredItem.page(params[:page]).where(is_deleted: false).reverse_order
  end
  
  def search
    keywords = params[:keyword].split(/[[:blank:]]+/).select(&:present?)
    @range = params[:range]
    if keywords.present?
      if @range == "全て"
        bartered_items_false = BarteredItem.where(is_deleted: false)
        keywords.inject(bartered_items_false) do |bartered_items,keyword|
          @items = bartered_items.where("title like?", "%#{keyword}%").or(bartered_items.where("explanation like?", "%#{keyword}%"))
        end
        @bartered_items = @items.distinct.page(params[:page]).reverse_order
        @keyword = params[:keyword]
        render "index"
      elsif @range == "募集中"
        bartered_items_false = BarteredItem.where(is_deleted: false).where(barter_status: 0)
        keywords.inject(bartered_items_false) do |bartered_items,keyword|
          @items = bartered_items.where("title like?", "%#{keyword}%").or(bartered_items.where("explanation like?", "%#{keyword}%"))
        end
        @bartered_items = @items.distinct.page(params[:page]).reverse_order
        @keyword = params[:keyword]
        render "index"
      else
        bartered_items_false = BarteredItem.where(is_deleted: false).where(barter_status: 1)
        keywords.inject(bartered_items_false) do |bartered_items,keyword|
          @items = bartered_items.where("title like?", "%#{keyword}%").or(bartered_items.where("explanation like?", "%#{keyword}%"))
        end
        @bartered_items = @items.distinct.page(params[:page]).reverse_order
        @keyword = params[:keyword]
        render "index"
      end
    else
      if @range == "全て"
        @bartered_items = BarteredItem.where(is_deleted: false).page(params[:page]).reverse_order
        render "index"
      elsif @range == "募集中"
        @bartered_items = BarteredItem.where(is_deleted: false).where(barter_status: 0).page(params[:page]).reverse_order
        render "index"
      elsif @range == "取引終了"
        @bartered_items = BarteredItem.where(is_deleted: false).where(barter_status: 1).page(params[:page]).reverse_order
        render "index"
      end
    end
  end
  
private
  def bartered_item_params
    params.require(:bartered_item).permit(:user_id, :title, :explanation, :barter_way, :desired_place, :no1_wanted_item_id, :no2_wanted_item_id, :no3_wanted_item_id, :barter_status, bartered_item_images_images: [])
  end

end

app/helpers/bartered_items_helper.rb
module BarteredItemsHelper
end

app/views/bartered_items/_bookmark.html.erb
<% if user_signed_in? %>
  <% if bartered_item.bookmarked_by?(current_user) %>
    <%= link_to bartered_item_bookmarks_path(bartered_item), method: :delete, remote: true do %>
      <i class="fas fa-bookmark fa-lg"></i>
    <% end %>
  <% else %>
    <%= link_to bartered_item_bookmarks_path(bartered_item), method: :post, remote: true do %>
      <i class="far fa-bookmark fa-lg"></i>
    <% end %>
  <% end %>
<% end %>

app/views/bartered_items/edit.html.erb
<div class='container'>
  
  <div class="row" style="margin:30px 50px 40px 20px">
    <div class="col-lg-4 offset-lg-3 heading">
      <h3 style="text-align: center;">譲渡グッズ　編集</h3>
    </div>
  </div>
  
  <%= form_with model:@bartered_item, local:true do |f| %>
  <div class='row'>
    <div class="col-lg-2 heading">画像アップロード</div>
    <div class="col-lg-2">
      <div class="form-group">
        <%= f.attachment_field :bartered_item_images_images, multiple: true %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-lg-2 col-lg-10 form-group">
      (画像を複数選択するには「shift + クリック」または「ctrl + クリック」)
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-2 heading">タイトル</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :title, class:"form-control",id:"input_title" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">譲渡グッズ詳細</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :explanation, class:"form-control", id:"input_explanation"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">交換方法</div>
    <div class="col-lg-4">
      <div class="form-group">
        <div class="barter-way"><%= f.radio_button :barter_way, :郵送のみ %></div>
        <div class="barter-way"><%= f.label :barter_way, '郵送のみ' %></div>
        <div class="barter-way"><%= f.radio_button :barter_way, :手渡しのみ %></div>
        <div class="barter-way"><%= f.label :barter_way, '手渡しのみ' %></div>
        <div class="barter-way"><%= f.radio_button :barter_way, :郵送・手渡し両方可%></div>
        <div class="barter-way"><%= f.label :barter_way, '郵送・手渡し両方可' %></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">交換希望場所</div>
    <div class="col-lg-4">
      <div>
        <%= f.select :desired_place, BarteredItem.desired_places.keys, {} %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-2 heading">お探しアイテム（１）</div>
    <div class="col-lg-4">
      <div>
		    <%= f.select :no1_wanted_item_id, options_from_collection_for_select(current_user.wanted_items, :id, :title, @bartered_item.no1_wanted_item_id), prompt: "お探しアイテムから選択してください" %>
		  </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">お探しアイテム（２）</div>
    <div class="col-lg-4">
      <div>
		    <%= f.select :no2_wanted_item_id, options_from_collection_for_select(current_user.wanted_items, :id, :title, @bartered_item.no2_wanted_item_id), prompt: "お探しアイテムから選択してください" %>
		  </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">お探しアイテム（３）</div>
    <div class="col-lg-4">
      <div>
		    <%= f.select :no3_wanted_item_id, options_from_collection_for_select(current_user.wanted_items, :id, :title, @bartered_item.no3_wanted_item_id), prompt: "お探しアイテムから選択してください" %>
		  </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-2 heading">取引状態</div>
    <div class="col-lg-4">
      <div>
        <%= f.select :barter_status, BarteredItem.barter_statuses.keys, {} %>
      </div>
    </div>
  </div>
  <div class="row" style="margin:30px 10px 0px 10px">
    <div class="col-lg-2 offset-lg-3 heading">    
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "更新",class:"btn btn-warning" %>
      <% end %>
    </div>
    <div class="col-lg-2 heading">
        <%= link_to "削除", barter_delete_path,method: :patch,"data-confirm" => "削除しますか", class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/bartered_items/index.html.erb
<div class="container">
  <% if @keyword or @range %>
    <h3 class="heading"><%= "検索結果:#{@bartered_items.count}件、""検索条件（取引状態：#{@range},キーワード：#{@keyword}）" %></h3>
  <% else %>
    <h3 class="heading"><%= "譲渡グッズ　一覧:#{@bartered_items.count}件"%></h3>
  <% end %>
  <div class="row">
    <% if @bartered_items.present? %>
      <% @bartered_items.each do |bartered_item| %>
        <div class="col-lg-3 index-item">
          <table class="table table-bordered item-table">
            <tr>
              <td class="text-center">
                <%= link_to bartered_item_path(bartered_item.id) do %>
                  <% if bartered_item.bartered_item_images.present? %>
                    <% bartered_item.bartered_item_images.first(1).each do |image| %>
                      <%= attachment_image_tag image, :image, :fill, 200, 200, fallback: image_url("no_image.jpg")%>
                    <% end %>
                  <% else %>
                    <%= attachment_image_tag bartered_item.bartered_item_images.first, :image, class: "img-fluid", fallback: image_url("no_image.jpg")%>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                出品者:<%= link_to user_path(bartered_item.user) do %><%= bartered_item.user.nick_name %><% end %>
              </td>
            </tr>          
            <tr>
              <td>
                <%= link_to bartered_item_path(bartered_item.id) do %>
                  <%= truncate(bartered_item.title, length: 29) %>
                <% end %>
                <span class="bartered_item-<%= bartered_item.id %>">
                  <%= render "bookmark", bartered_item: bartered_item %>
                </span>
              </td>
            </tr>
            <% if bartered_item.barter_status == "取引終了" %>
              <tr>
                <td class="trade-finish text-center"><%= bartered_item.barter_status %></th>
              </tr>
            <% else %>
              <tr>
                <td class="trade-unfinish text-center"><%= bartered_item.barter_status %></th>
              </tr>
            <% end %>
          </table> 
        </div>
      <% end %>
    <% else %>
      <div class="col-lg-4 heading">該当するグッズはありません</div>
    <% end %>
  </div>
  
  <%= paginate @bartered_items %>
  
</div>

app/views/bartered_items/new.html.erb
<div class='container'>
  
  <% if @bartered_item.errors.any? %>
    <div id="error_explanation">
      <h3><%= @bartered_item.errors.count %>件のエラーがあります</h3>
      <ul>
        <% @bartered_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row" style="margin:30px 50px 40px 20px">
    <div class="col-lg-4 offset-lg-3">
      <h3 class="heading" style="text-align: center;">譲渡グッズ 新規追加</h3>
    </div>
  </div>
  
  <%= form_with model:@bartered_item, local:true do |f| %>
  <div class='row'>
    <div class="col-lg-2 heading">画像アップロード</div>
    <div class="col-lg-2">
      <div class="form-group">
        <%= f.attachment_field :bartered_item_images_images, multiple: true %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-lg-2 col-lg-10 form-group">
      (画像を複数選択するには「shift + クリック」または「ctrl + クリック」)
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-2 heading">タイトル</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :title, class:"form-control",id:"input_title" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">譲渡グッズ詳細</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :explanation, class:"form-control", id:"input_explanation"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">交換方法</div>
    <div class="col-lg-10">
      <div class="form-group">
        <div class="barter-way"><%= f.radio_button :barter_way, :郵送のみ %></div>
        <div class="barter-way"><%= f.label :barter_way, '郵送のみ' %></div>
        <div class="barter-way"><%= f.radio_button :barter_way, :手渡しのみ %></div>
        <div class="barter-way"><%= f.label :barter_way, '手渡しのみ' %></div>
        <div class="barter-way"><%= f.radio_button :barter_way, :郵送・手渡し両方可%></div>
        <div class="barter-way"><%= f.label :barter_way, '郵送・手渡し両方可' %></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">交換希望場所</div>
    <div class="col-lg-4">
      <div>
        <%= f.select :desired_place, BarteredItem.desired_places.keys, {} %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-2 heading">お探しアイテム（１）</div>
    <div class="col-lg-4">
      <div>
		    <%= f.select :no1_wanted_item_id, options_from_collection_for_select(current_user.wanted_items, :id, :title), prompt: "お探しアイテムから選択してください" %>
		  </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">お探しアイテム（２）</div>
    <div class="col-lg-4">
      <div>
		    <%= f.select :no2_wanted_item_id, options_from_collection_for_select(current_user.wanted_items, :id, :title), prompt: "お探しアイテムから選択してください" %>
		  </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">お探しアイテム（３）</div>
    <div class="col-lg-4">
      <div>
		    <%= f.select :no3_wanted_item_id, options_from_collection_for_select(current_user.wanted_items, :id, :title), prompt: "お探しアイテムから選択してください" %>
		  </div>
    </div>
  </div>
  <div class="row" style="margin:30px 10px 0px 10px">
    <div class="col-lg-4 offset-lg-3 heading">    
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "作成",class:"btn btn-warning btn-lg btn-block"%>
      <% end %>
    </div>
  </div>
</div>

app/views/bartered_items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
        <% if @bartered_item.bartered_item_images.present? %>
          <span class="slider">
            <% @bartered_item.bartered_item_images.each do |image| %>
              <span><%= attachment_image_tag image, :image, class: "img-fluid", fallback: image_url("no_image.jpg") %></span>
            <% end %>
          </span>
        <% else %>
            <span><%= attachment_image_tag @bartered_item.bartered_item_images.first, :image, class: "img-fluid", fallback: image_url("no_image.jpg") %></span>
        <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 item-show">
      <h4 class="heading" style="display: inline-block;">
        譲渡アイテム　詳細
      </h4>
      <div class="bartered_item-<%= @bartered_item.id %>" style="display: inline-block;" >
        <%= render "bookmark", bartered_item: @bartered_item %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
    <h5>
      出品者：<%= link_to user_path(@bartered_item.user) do %><%= "#{@bartered_item.user.nick_name}さん" %><% end %>
    </h5>
    <% if user_signed_in? %>
      <% unless current_user == @user %>
        <span id="user-<%= @user.id %>">
          <%= render "users/follow", user: @user %>
        </span>
        <span style="display: inline-block;">
          <% if @isRoom == true %>
            <%= link_to room_path(@roomID) do%>
              <i class="fas fa-envelope fa-lg"></i>
            <% end %>
          <% else %>
            <%= form_with model:@room, local:true do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.button :type => "submit", style: 'border-style: none; background: none;' do %>
                <i class="far fa-envelope fa-lg"></i>
              <% end %>
            <% end %>
          <% end %>
        </span>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <table class="table">
      <tbody>
        <tr>
          <th class="align-middle", style="width: 144px"><div class="text-center">タイトル</div></th>
          <th><div class="text-left"><%= @bartered_item.title %></div></th>
        </tr>
        <tr>
          <th class="align-middle"><div class="text-center">説明</div></th>
          <th><%= @bartered_item.explanation%></th>
        </tr>
        <tr>
          <th><div class="text-center">希望交換方法</div></th>
          <th><%= @bartered_item.barter_way %></th>
        </tr>
        <tr>
          <th><div class="text-center">希望交換場所</div></th>
          <th><%= @bartered_item.desired_place %></th>
        </tr>
        <% if @bartered_item.barter_status == "取引終了" %>
          <tr>
            <th><div class="text-center">取引状態</div></th>
            <th class="trade-finish"><%= @bartered_item.barter_status %></th>
          </tr>
        <% else %>
          <tr>
            <th><div class="text-center">取引状態</div></th>
            <th class="trade-unfinish"><%= @bartered_item.barter_status %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-lg-12">
       <h5><%= "#{@bartered_item.user.nick_name}さんの現在探し中グッズベスト3" %></h5>
    </div>
  </div>



    <div class="row border border-secondary rounded mypage-row">
    <% @wanted_items.each do |item| %>
      <div class="col-lg-4">
        <table class="table table-bordered item-table">
          <tr>
            <td class="text-center">
              <%= link_to wanted_item_path(item) do %>
                <% if item.wanted_item_images.present? %>
                  <% item.wanted_item_images.first(1).each do |image| %>
                    <%= attachment_image_tag image, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                  <% end %>
                <% else %>
                  <%= attachment_image_tag item.wanted_item_images.first, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to wanted_item_path(item) do %>
                <%= truncate(item.title, length: 29) %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
    <% end %>
    <div class="col-lg-3 offset-lg-9">
      <div class="text-right">
        <%= link_to "欲しいモノリスト一覧へ", wants_path(@bartered_item.user),class: "btn btn-light"%>
      </div>
    </div>
  </div>

  <% if current_user == @user %>
    <div class="row">
      <div class="col-lg-1 offset-lg-11">
        <div class="edit-button text-right">
          <%= link_to "編集", edit_bartered_item_path, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row comment-counts">
    <div>
      <i class="fas fa-comments fa-lg", id="comment-counts-<%= @bartered_item.id %>">コメント：<%= @bartered_item.bartered_item_comments.count %>件</i>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="row">
      <div class="col-lg-12">
        <%= form_with(model:[@bartered_item,@bartered_item_comment]) do |f| %>
          <div class="form-group-comment">
            <%= f.text_area :comment, class:"form-control" ,placeholder:"コメント", id:"input_comment" %>
            <div class="text-right">
              <%= f.button :type => "submit", style: 'border-style: none; background-color: rgb( 255, 191, 0);border-radius: 0.80rem;' do %>
                <i class="fas fa-paper-plane fa-lg"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <p>ログイン後、コメントできます</p>
  <% end %>

  <div class="comments">
    <%= render "bartered_item_comments/comment", bartered_item: @bartered_item %>
  </div>

</div>

<script>
  $(document).on('turbolinks:load', function() {
    $(function() {
        $('.slider').slick({
        arrows: false,
        dots: true,
        });
        $('.slick-dots li').on('mouseover', function() {
        $('.slider').slick('goTo', $(this).index());
        });
    });
  });
</script>