config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :users, except: [:index, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/delete' => 'users#delete', as: 'delete'
  get '/users/:id/confirm' => 'users#confirm', as: 'confirm'
  get '/users/:id/barters' => 'users#barter', as: 'barters'
  get '/users/:id/wants' => 'users#want', as: 'wants'
  get '/users/:id/bookmarks' => 'users#bookmark', as: 'bookmarks'
  get '/users/:id/rooms' => 'users#room', as: 'users_rooms'
  
  resources :bartered_items, except: [:destroy] do
   resource :bookmarks,only: [:create, :destroy]
   resources :bartered_item_comments, only: [:create, :destroy]
  end
  patch 'bartered_items/:id/delete' => 'bartered_items#delete', as: 'barter_delete'
  get 'search' => 'bartered_items#search'
  
  resources :wanted_items, except: [:index]
  
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  
  
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :image
  
  validates :nick_name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 1000 }
  
  has_many :bartered_items, dependent: :destroy
  has_many :bartered_item_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :wanted_items, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers,  through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
 #参考URLhttps://qiita.com/yuto_1014/items/358d0a425193b12c969a
  
  enum barter_way:{郵送のみ:0,手渡しのみ:1,郵送・手渡し両方可:2}
  enum desired_place:{
     郵送:0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
     }
  enum barter_status:{募集中:0, 取引終了:1}
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  before_action :reject_user, only: [:create]

protected

  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:notice] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:notice] = "必須項目を入力してください。"
    end
  end
  #参考URLhttps://qiita.com/yuto_1014/items/358d0a425193b12c969a
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @bartered_items = BarteredItem.where(is_deleted: false).where(user_id: @user.id).last(4).reverse
    @wanted_items = WantedItem.where(user_id: @user.id).last(4).reverse
    @bookmarks = Bookmark.where(user_id: @user.id).last(4).reverse
    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user == current_user
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id
              @isRoom = true
              @roomID = cu.room_id
            end
          end
        end
        unless @isRoom
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(@user)
    end
  end
  
  def update
    @user =User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  def delete
    @user = current_user
    @user.update(is_deleted: true) #is_deletedをfalseからtrueへ変更し、論理削除
    reset_session #セッション情報のリセットする
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end
  
  def confirm
  end

  def barter
    @bartered_items = BarteredItem.where(is_deleted: false).where(user_id: params[:id]).page(params[:page]).reverse_order
  end

  def want
    @wanted_items = WantedItem.where(user_id: params[:id]).page(params[:page]).reverse_order
  end

  def bookmark
    @bookmarks =Bookmark.where(user_id: current_user.id).page(params[:page]).reverse_order
  end
  
  def room
    @entries = Entry.where(user_id: current_user.id)
    @entries2 = Entry.none
    @entries.each do |entry|
      @entries2 += Entry.where(room_id: entry.room_id).where.not(user_id: current_user.id)#####where.notで指定以外を取得(参考https://www.sejuku.net/blog/13363）#####
    end
  end
  
  def user_params
    params.require(:user).permit(:email, :nick_name, :introduction, :barter_way, :desired_place, :image)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if current_user.following?(user) %>
  <%= link_to user_relationships_path(user.id), method: :delete, remote: true do %>
    <i class="fas fa-user-check fa-lg"></i>
  <% end %>
<% else %>
  <%= link_to user_relationships_path(user.id), method: :post, remote: true do %>
    <i class="far fa-user fa-lg"></i>
  <% end %>
<% end %>

app/views/users/barter.html.erb
<div class="container">
  <% if @bartered_items.present? %>
    <div class="row">
      <% @bartered_items.first(1).each do |bartered_item| %>
        <h5 class="heading">
          <%= link_to user_path(bartered_item.user) do %>
              <%= "#{bartered_item.user.nick_name}" %>
            <% end %>さんの譲渡グッズ一覧<%= "：#{@bartered_items.count}件" %>
        </h5>
      <% end %>
    </div>
    <div class="row">
      <% @bartered_items.each do |bartered_item| %>
        <div class="col-lg-3 index-item">
          <table class="table table-bordered item-table">
            <tr>
              <td class="text-center">
                <%= link_to bartered_item_path(bartered_item.id) do %>
                  <% if bartered_item.bartered_item_images.present? %>
                    <% bartered_item.bartered_item_images.last(1).each do |image| %>
                      <%= attachment_image_tag image, :image, :fill, 200, 200, fallback: image_url("no_image.jpg")%>
                    <% end %>
                  <% else %>
                    <%= attachment_image_tag bartered_item.bartered_item_images.first, :image, class: "img-fluid", fallback: image_url("no_image.jpg")%>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                <%= link_to bartered_item_path(bartered_item.id) do %>
                  <%= truncate(bartered_item.title, length: 29) %>
                <% end %>
                <span class="bartered_item-<%= bartered_item.id %>">
                  <%= render "bartered_items/bookmark", bartered_item: bartered_item %>
                </span>
              </td>
            </tr>
            <% if bartered_item.barter_status == "取引終了" %>
              <tr>
                <td class="trade-finish text-center"><%= bartered_item.barter_status %></th>
              </tr>
            <% else %>
              <tr>
                <td class="trade-unfinish text-center"><%= bartered_item.barter_status %></th>
              </tr>
            <% end %>
          </table> 
        </div>
      <% end %>
    </div>
    <%= paginate @bartered_items %>
  <% else %>
    <h5 class="heading">譲渡グッズはありません</h5>
  <% end %>
</div>

app/views/users/bookmark.html.erb
<div class="container">
  <% if @bookmarks.present? %>
    <div class="row">
      <% @bookmarks.first(1).each do |bookmark| %>
        <h5 class="heading">
          <%= link_to user_path(bookmark.user) do %>
              <%= "#{bookmark.user.nick_name}" %>
            <% end %>さんのブックマーク一覧<%= "：#{@bookmarks.count}件" %>
        </h5>
      <% end %>
    </div>
    <div class="row">
      <% @bookmarks.each do |bookmark| %>
        <div class="col-lg-3 index-item">
          <table class="table table-bordered item-table">
            <tr>
              <td class="text-center">
                <%= link_to bartered_item_path(bookmark.bartered_item.id) do %>
                  <% if bookmark.bartered_item.bartered_item_images.present? %>
                    <% bookmark.bartered_item.bartered_item_images.first(1).each do |image| %>
                      <%= attachment_image_tag image, :image, :fill, 200, 200, fallback: image_url("no_image.jpg")%>
                    <% end %>
                  <% else %>
                    <%= attachment_image_tag bookmark.bartered_item.bartered_item_images.first, :image, class: "img-fluid", fallback: image_url("no_image.jpg")%>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                出品者:<%= link_to user_path(bookmark.bartered_item.user) do %><%= bookmark.bartered_item.user.nick_name %><% end %>
              </td>
            </tr>          
            <tr>
              <td>
                <%= link_to bartered_item_path(bookmark.bartered_item.id) do %>
                  <%= truncate(bookmark.bartered_item.title, length: 29) %>
                <% end %>
                <span class="bartered_item-<%= bookmark.bartered_item.id %>">
                  <%= render "bartered_items/bookmark", bartered_item: bookmark.bartered_item %>
                </span>
              </td>
            </tr>
            <% if bookmark.bartered_item.barter_status == "取引終了" %>
              <tr>
                <td class="trade-finish text-center"><%= bookmark.bartered_item.barter_status %></th>
              </tr>
            <% else %>
              <tr>
                <td class="trade-unfinish text-center"><%= bookmark.bartered_item.barter_status %></th>
              </tr>
            <% end %>
          </table> 
        </div>
      <% end %>
    </div>
    <%= paginate @bookmarks %>
  <% else %>
    <h5 class="heading">ブックマークはありません</h5>
  <% end %>
</div>

app/views/users/confirm.html.erb
<div style="margin:10% 0;">
  <h4 style="text-align:center">本当に退会しますか？</h3>

  </br>

  <P style="text-align:center">退会すると、ログインや</br>マイページなどが閲覧できなくなります。</br>退会する場合は、「退会する」をクリックしてください</P>

  <p style="text-align:center">
    <%= link_to "退会しない", user_path(current_user), class: "btn btn-primary" %>
    <%= link_to "退会する", delete_path,method: :patch,"data-confirm" => "退会手続きを行います", class: "btn btn-danger" %>
  </p>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class="row">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h3><%= @user.errors.count %>件のエラーがあります</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="row" style="margin:30px 50px 40px 20px">
    <div class="col-lg-4 offset-lg-3">
      <h3 style="text-align: center;">登録情報　編集</h3>
    </div>
  </div>
  
  <%= form_with model:@user, local:true do |f| %>
  <div class='row'>
    <div class="col-lg-2">画像アップロード</div>
    <div class="col-lg-4">
      <%= f.attachment_field :image, placeholder: "プロフィール画像" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-2">ニックネーム</div>
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.text_field :nick_name, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">自己紹介</div>
    <div class="col-lg-8">
      <div class="form-group">
        <%= f.text_area :introduction, class:"form-control", id:"input_introduction"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">交換方法</div>
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.radio_button :barter_way, :郵送のみ %>
        <%= f.label :barter_way, '郵送のみ' %>
        <%= f.radio_button :barter_way, :手渡しのみ %>
        <%= f.label :barter_way, '手渡しのみ' %>
        <%= f.radio_button :barter_way, :郵送・手渡し両方可%>
        <%= f.label :barter_way, '郵送・手渡し両方可' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">交換希望場所</div>
    <div class="col-lg-4">
      <div>
        <%= f.select :desired_place, User.desired_places.keys, {} %>
      </div>
    </div>
  </div>
  <br>

  <div class="row" style="margin:30px 10px 0px 10px">
    <div class="col-lg-2 offset-lg-3">    
      <%= f.submit "更新",class:"btn btn-warning" %>
      <% end %>
    </div>
    <div class="col-lg-2">
        <%= link_to "退会する", confirm_path(@user), class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/room.html.erb
<div class="container">
  <div class="row">
    <h5 class="heading">チャットルーム一覧</h5>
  </div>
  <div class="row">
    <table class="table">
      <tbody>
        <% if @entries2.present? %>
          <% @entries2.each do |entry| %>
              <tr>
                <td class="col-lg-2"><%= link_to "#{entry.user.nick_name}さん", user_path(entry.user) %></td>
                <% if entry.room.messages.present? %>
                  <td class="col-lg-8"><%= truncate(entry.room.messages.last.content, length: 200) %></td>
                <% else %>
                  <td>メッセージはありません</td>
                <% end %>
                <td class="col-lg-2"><%= link_to "チャットへ", room_path(entry.room_id), class:"btn btn-primary" %></td>
              </tr>
          <% end %>
        <% else %>
          <h6>チャットルームはありません</h6>
        <% end %>
      </tbody>
    </table>
   </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row border border-secondary rounded">
    <div class="col-lg-3 text-center">
      <div><%= attachment_image_tag @user, :image, class: "img-fluid", fallback: image_url("no_image.jpg") %></div>
      <% if user_signed_in? %> 
        <% if @user == current_user %>
          <div><%= link_to "チャットルーム一覧", users_rooms_path(@user)%></div>
        <% else %>
          <div style="padding: 0 20px 0 0">
            <span id="user-<%= @user.id %>">
              <%= render "users/follow", user: @user %>
            </span>
            <span style="display: inline-block;">
              <% if @isRoom == true %>
                <%= link_to room_path(@roomID) do%>
                  <i class="fas fa-envelope fa-lg"></i>
                <% end %>
              <% else %>
                <%= form_with model:@room, local:true do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, value: @user.id %>
                  <% end %>
                  <%= f.button :type => "submit", style: 'border-style: none; background: none;' do %>
                    <i class="far fa-envelope fa-lg"></i>
                  <% end %>
                <% end %>
              <% end %>
            </span>
          </div>      
        <% end %>
      <% end %>
      <div>
        <sapn><%= link_to "フォロー：#{@user.followings.count}", user_followings_path(@user.id) %></span>
        <saon><%= link_to "フォロワー：#{@user.followers.count}", user_followers_path(@user.id) %></span>
      </div>
    </div>
    <div class="col-lg-9">
      <table class="table profiel-area">
        <tr>
          <td><h5><%= "#{@user.nick_name}さん" %></h5></td>
        </tr>
        <tr>
          <td class="mypage-icon"><%= "希望交換方法：#{@user.barter_way}" %></td>
          <td class="mypage-icon"><%= "希望交換場所：#{@user.desired_place}" %></td>
        </tr>
      </table>
    </div>
    <% if @user.introduction.present? %>
      <div class="col-lg-12">
        <div class="introduction">
          <%= "#{@user.introduction}" %>
        </div>
      </div>
    <% end %>
  </div>
  
  <% if current_user == @user %>  
    <div class="row">
      <div class="col-lg-1 offset-lg-11">
        <div class="edit-button text-right">
          <%= link_to "編集", edit_user_path, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  <% end %>

  <p></p>
  
  <h5 class="heading">譲渡グッズ</h5>
  <div class="row border border-secondary rounded mypage-row">
    <% if @bartered_items.present? %>
      <% @bartered_items.each do |item| %>
        <div class="col-lg-3">
          <table class="table table-bordered item-table">
            <tr>
              <td class="text-center">
                <%= link_to bartered_item_path(item) do %>
                  <% if item.bartered_item_images.present? %>
                    <% item.bartered_item_images.first(1).each do |image| %>
                      <%= attachment_image_tag image, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                    <% end %>
                  <% else %>
                    <%= attachment_image_tag item.bartered_item_images.first, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                <%= link_to bartered_item_path(item) do %>
                  <%= truncate(item.title, length: 29) %>
                <% end %>
                <span class="bartered_item-<%= item.id %>">
                  <%= render "bartered_items/bookmark", bartered_item: item %>
                </span>
              </td>
            </tr>
            <% if item.barter_status == "取引終了" %>
              <tr>
                <td class="trade-finish text-center"><%= item.barter_status %></th>
              </tr>
            <% else %>
              <tr>
                <td class="trade-unfinish text-center"><%= item.barter_status %></th>
              </tr>
            <% end %>
          </table> 
        </div>
      <% end %>
      <div class="col-lg-1 offset-lg-11"><%= link_to "一覧", barters_path(@user), class: "btn btn-light" %></div>
    <% else %>
      <p>グッズはありません</p>
    <% end %>
  </div>
  
  <p></p>
  
  <h5 class="heading">お探しグッズ</h5>
  <div class="row border border-secondary rounded mypage-row">
    <% if @wanted_items.present? %>
      <% @wanted_items.each do |item| %>
        <div class="col-lg-3">
          <table class="table table-bordered item-table">
            <tr>
              <td class="text-center">
                <%= link_to wanted_item_path(item) do %>
                  <% if item.wanted_item_images.present? %>
                    <% item.wanted_item_images.first(1).each do |image| %>
                      <%= attachment_image_tag image, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                    <% end %>
                  <% else %>
                    <%= attachment_image_tag item.wanted_item_images.first, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                <%= link_to wanted_item_path(item) do %>
                  <%= truncate(item.title, length: 29) %>
                <% end %>
              </td>
            </tr>
          </table> 
        </div>
      <% end %>
      <div class="col-lg-1 offset-lg-11"><%= link_to "一覧", wants_path(@user), class: "btn btn-light" %></div>
    <% else %>
       <p>グッズはありません</p>
    <% end %>
  </div>
  
  <p></p>
  
  <% if current_user == @user %>
    <h5 class="heading">ブックマーク</h5>
    <div class="row border border-secondary rounded mypage-row">
      <% if @bookmarks.present? %>
        <% @bookmarks.each do |bookmark| %>
          <div class="col-lg-3">
            <table class="table table-bordered item-table">
              <tr>
                <td class="text-center">
                  <%= link_to bartered_item_path(bookmark.bartered_item) do %>
                    <% if bookmark.bartered_item.bartered_item_images.present? %>
                      <% bookmark.bartered_item.bartered_item_images.first(1).each do |image| %>
                        <%= attachment_image_tag image, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                      <% end %>
                    <% else %>
                      <%= attachment_image_tag bookmark.bartered_item.bartered_item_images.first, :image, :fill, 200, 200, class: "img-fluid",fallback: image_url("no_image.jpg") %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>
                  出品者:<%= link_to user_path(bookmark.bartered_item.user) do %><%= bookmark.bartered_item.user.nick_name %><% end %>
                </td>
              </tr> 
              <tr>
                <td>
                  <%= link_to bartered_item_path(bookmark.bartered_item) do %>
                    <%= truncate(bookmark.bartered_item.title, length: 29) %>
                  <% end %>
                  <span class="bartered_item-<%= bookmark.bartered_item.id %>">
                    <%= render "bartered_items/bookmark", bartered_item: bookmark.bartered_item %>
                  </span>
                </td>
              </tr>
              <% if bookmark.bartered_item.barter_status == "取引終了" %>
                <tr>
                  <td class="trade-finish text-center"><%= bookmark.bartered_item.barter_status %></th>
                </tr>
              <% else %>
                <tr>
                  <td class="trade-unfinish text-center"><%= bookmark.bartered_item.barter_status %></th>
                </tr>
              <% end %>
            </table> 
          </div>
        <% end %>
        <div class="col-lg-1 offset-lg-11"><%= link_to "一覧", bookmarks_path(@user), class: "btn btn-light" %></div>
      <% else %>
        <p>ブックマークはありません</p>
      <% end %>
    </div>
  <% end %>
</div>