config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :users, except: [:index, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/delete' => 'users#delete', as: 'delete'
  get '/users/:id/confirm' => 'users#confirm', as: 'confirm'
  get '/users/:id/barters' => 'users#barter', as: 'barters'
  get '/users/:id/wants' => 'users#want', as: 'wants'
  get '/users/:id/bookmarks' => 'users#bookmark', as: 'bookmarks'
  get '/users/:id/rooms' => 'users#room', as: 'users_rooms'
  
  resources :bartered_items, except: [:destroy] do
   resource :bookmarks,only: [:create, :destroy]
   resources :bartered_item_comments, only: [:create, :destroy]
  end
  patch 'bartered_items/:id/delete' => 'bartered_items#delete', as: 'barter_delete'
  get 'search' => 'bartered_items#search'
  
  resources :wanted_items, except: [:index]
  
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  
  
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  
end

app/models/wanted_item.rb
class WantedItem < ApplicationRecord
  
  validates :title, presence: true
  validates :explanation, presence: true
  
  belongs_to :user
  has_many :wanted_item_images, dependent: :destroy
  accepts_attachments_for :wanted_item_images, attachment: :image
end

app/controllers/wanted_items_controller.rb
class WantedItemsController < ApplicationController
  
  def new
    @wanted_item = WantedItem.new
  end
  
  def create
    @wanted_item = WantedItem.new(wanted_item_params)
    @wanted_item.user_id = current_user.id
    if @wanted_item.save
      redirect_to wanted_item_path(@wanted_item.id)
    else
      render :new
    end
  end
  
  def show
    @wanted_item = WantedItem.find(params[:id])
  end

  def edit
    if WantedItem.find(params[:id]).present?
      @wanted_item = WantedItem.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
  def update
    @wanted_item = WantedItem.find(params[:id])
    @wanted_item.update(wanted_item_params)
    redirect_to wanted_item_path(@wanted_item.id)
  end
  
  def destroy
    @wanted_item = WantedItem.find(params[:id])
    @wanted_item.destroy
    redirect_to wants_path(current_user)
  end

private

  def wanted_item_params
    params.require(:wanted_item).permit(:title, :explanation, wanted_item_images_images: [])
  end
  
  
end

app/helpers/wanted_items_helper.rb
module WantedItemsHelper
end

app/views/wanted_items/edit.html.erb
<div class='container'>
  
  <div class="row" style="margin:30px 50px 40px 20px">
    <div class="col-lg-4 offset-lg-3">
      <h3 class="heading" style="text-align: center;">お探しアイテム　編集</h3>
    </div>
  </div>
  
  <%= form_with model:@wanted_item, local:true do |f| %>
  <div class='row'>
    <div class="col-lg-2 heading">画像アップロード</div>
    <div class="col-lg-2">
      <div class="form-group">
        <%= f.attachment_field :wanted_item_images_images, multiple: true %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-lg-2 col-lg-10 form-group">
      (画像を複数選択するには「shift + クリック」または「ctrl + クリック」)
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-2 heading">タイトル</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :title, class:"form-control",id:"input_title" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">譲渡グッズ詳細</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :explanation, class:"form-control", id:"input_explanation"%>
      </div>
    </div>
  </div>
  <div class="row" style="margin:30px 10px 0px 10px">
    <div class="col-lg-2 offset-lg-3 heading">    
      <%= f.submit "更新",class:"btn btn-warning" %>
      <% end %>
    </div>
    <div class="col-lg-2 heading">
        <%= link_to "削除", wanted_item_path, method: :delete,"data-confirm" => "削除しますか", class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/wanted_items/new.html.erb
<div class='container'>

  <% if @wanted_item.errors.any? %>
    <div id="error_explanation">
      <h3><%= @wanted_item.errors.count %>件のエラーがあります</h3>
      <ul>
        <% @wanted_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row" style="margin:30px 50px 40px 20px">
    <div class="col-lg-4 offset-lg-3">
      <h3 class="heading" style="text-align: center;">お探しグッズ　新規追加</h3>
    </div>
  </div>
  
  <%= form_with model:@wanted_item, local:true do |f| %>
  <div class='row'>
    <div class="col-lg-2 heading">画像アップロード</div>
    <div class="col-lg-2">
      <div class="form-group">
        <%= f.attachment_field :wanted_item_images_images, multiple: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="offset-lg-2 col-lg-10 form-group">
      (画像を複数選択するには「shift + クリック」または「ctrl + クリック」)
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">タイトル</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :title, class:"form-control",id:"input_title" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 heading">お探しグッズ詳細</div>
    <div class="col-lg-7">
      <div class="form-group">
        <%= f.text_area :explanation, class:"form-control", id:"input_explanation"%>
      </div>
    </div>
  </div>
  <div class="row" style="margin:30px 10px 0px 10px">
    <div class="col-lg-4 offset-lg-3 heading">    
      <%= f.submit "作成",class:"btn btn-warning btn-lg btn-block"%>
      <% end %>
    </div>
  </div>
</div>

app/views/wanted_items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div>
        <% if @wanted_item.wanted_item_images.present? %>
          <div class="slider">
            <% @wanted_item.wanted_item_images.each do |image| %>
              <div>
                <%= attachment_image_tag image, :image, class: "img-fluid", fallback: image_url("no_image.jpg")%>
              </div>
            <% end %>
          </div>
        <% else %>
          <span><%= attachment_image_tag @wanted_item.wanted_item_images.first, :image, class: "img-fluid", fallback: image_url("no_image.jpg") %></span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 item-show">
      <h4 class="heading" style="display: inline-block;">
        お探しグッズ　詳細
      </h4>
    </div>
  </div>

  <div class="row">
    <h5 class="col-lg-12">
      探し主：<%= link_to user_path(@wanted_item.user) do %><%= @wanted_item.user.nick_name %><% end %>
    </5>
  </div>

  <div class="row">
    <table class="table">
      <tbody>
        <tr>
          <th class="align-middle", style="width: 144px"><div class="text-center">タイトル</div></th>
          <th><div class="text-left"><%= @wanted_item.title %></div></th>
        </tr>
        <tr>
          <th class="align-middle"><div class="text-center">説明</div></th>
          <th><%= @wanted_item.explanation %></th>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-lg-4 offset-lg-8">
      <div class="edit-button text-right">
        <%= link_to "#{@wanted_item.user.nick_name}さんの欲しいモノリスト一覧へ", wants_path(@wanted_item.user),class: "btn btn-light" %>
      </div>
    </div>
  </div>

  <% if current_user == @wanted_item.user %>
    <div class="row">
      <div class="col-lg-1 offset-lg-11">
        <div class="edit-button text-right">
          <%= link_to "編集", edit_wanted_item_path(@wanted_item), class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  <% end %>

</div>

<script>
  $(document).on('turbolinks:load', function() {
    $(function() {
        $('.slider').slick({
        arrows: false,
        dots: true,
        });
        $('.slick-dots li').on('mouseover', function() {
        $('.slider').slick('goTo', $(this).index());
        });
    });
  });
</script>