config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :users, except: [:index, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/delete' => 'users#delete', as: 'delete'
  get '/users/:id/confirm' => 'users#confirm', as: 'confirm'
  get '/users/:id/barters' => 'users#barter', as: 'barters'
  get '/users/:id/wants' => 'users#want', as: 'wants'
  get '/users/:id/bookmarks' => 'users#bookmark', as: 'bookmarks'
  get '/users/:id/rooms' => 'users#room', as: 'users_rooms'
  
  resources :bartered_items, except: [:destroy] do
   resource :bookmarks,only: [:create, :destroy]
   resources :bartered_item_comments, only: [:create, :destroy]
  end
  patch 'bartered_items/:id/delete' => 'bartered_items#delete', as: 'barter_delete'
  get 'search' => 'bartered_items#search'
  
  resources :wanted_items, except: [:index]
  
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  
  
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bartered_item.rb
class BarteredItem < ApplicationRecord
  
  validates :title, presence: true
  validates :explanation, presence: true
  validates :barter_way, presence: true
  validates :desired_place, presence: true
  
  has_many :bartered_item_images, dependent: :destroy
  has_many :bartered_item_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  belongs_to :user
  accepts_attachments_for :bartered_item_images, attachment: :image
  
  enum barter_way:{郵送のみ:0,手渡しのみ:1,郵送・手渡し両方可:2}
  enum desired_place:{
     郵送:0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
     }
  enum barter_status:{募集中:0, 取引終了:1}
  
  def bookmarked_by?(user)
    bookmarks.where(user_id:user).exists?
  end
  
  
  
end

app/models/bartered_item_image.rb
class BarteredItemImage < ApplicationRecord
  belongs_to :bartered_item
  attachment :image
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  
  belongs_to :user
  belongs_to :bartered_item
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  
  validates :content, presence: true
  
  belongs_to :user
  belongs_to :room
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :image
  
  validates :nick_name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 1000 }
  
  has_many :bartered_items, dependent: :destroy
  has_many :bartered_item_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :wanted_items, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers,  through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
 #参考URLhttps://qiita.com/yuto_1014/items/358d0a425193b12c969a
  
  enum barter_way:{郵送のみ:0,手渡しのみ:1,郵送・手渡し両方可:2}
  enum desired_place:{
     郵送:0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
     }
  enum barter_status:{募集中:0, 取引終了:1}
  
end

app/models/wanted_item.rb
class WantedItem < ApplicationRecord
  
  validates :title, presence: true
  validates :explanation, presence: true
  
  belongs_to :user
  has_many :wanted_item_images, dependent: :destroy
  accepts_attachments_for :wanted_item_images, attachment: :image
end

app/models/wanted_item_image.rb
class WantedItemImage < ApplicationRecord
  belongs_to :wanted_item
  attachment :image
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @bartered_items = BarteredItem.where(is_deleted: false).last(4).reverse
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wanted_items_helper.rb
module WantedItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarterAnimeGoods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti&family=Patua+One&family=Zen+Kaku+Gothic+Antique:wght@300;400&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header style="background-color: #FFE28C;">
      <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand" href="/"><span class="text-dark logo">BarterAnimeGoods</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-around" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" aria-haspopup="true" aria-expanded="false">
                   <i class="fas fa-user-circle fa-lg"></i>アカウント
                  </a>
                  <div class="dropdown-menu mt-0" aria-labelledby="navbarDropdownMenuLink">
                    <%= link_to "マイページ", user_path(current_user), class:"dropdown-item" %>
                    <%= link_to "マイ譲渡グッズ", barters_path(current_user), class:"dropdown-item" %>
                    <%= link_to "マイお探しグッズ", wants_path(current_user), class:"dropdown-item" %>
                    <%= link_to "マイブックマーク", bookmarks_path(current_user), class:"dropdown-item" %>
                  </div>
                </li>
                <li class="dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" aria-haspopup="true" aria-expanded="false">
                   グッズ一覧・追加
                  </a>
                  <div class="dropdown-menu mt-0" aria-labelledby="navbarDropdownMenuLink">
                    <%= link_to "譲渡グッズ一覧", bartered_items_path, class:"dropdown-item" %>
                    <%= link_to "譲渡グッズ追加", new_bartered_item_path, class:"dropdown-item" %>
                    <%= link_to "お探しグッズ追加", new_wanted_item_path, class:"dropdown-item" %>
                  </div>
                </li>
                <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt"%></li>
                <li class="nav-item">
                  <%= form_with url: search_path, method: :get, local: true do |f| %>
                    <%= f.select :range, options_for_select([["全て"],["募集中"],["取引終了"]]) %>
                    <%= f.text_field :keyword, value: @keyword, class:"nav-search"%>
                    <%= f.button :type => "submit", style: 'border-style: none; background: none;' do %>
                      <i class="fas fa-search fa-lg"></i>
                    <% end %>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class:"fas fa-user-plus text-dark"%>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class:"fas fa-sign-in-alt text-dark"%>
                </li>
                <li class="nav-item">
                  <%= link_to "譲渡グッズ一覧", bartered_items_path, class:"text-dark" %>
                </li>
                <li class="nav-item">
                  <%= form_with url: search_path, method: :get, local: true do |f| %>
                    <%= f.text_field :keyword, value: @keyword, class:"nav-search"%>
                    <%= f.button :type => "submit", style: 'border-style: none; background: none;' do %>
                      <i class="fas fa-search fa-lg"></i>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
      </nav>
    </header>
    <main>
      <p id="notice"><%= notice %></p>

      <%= yield %>

    </main>
    <footer class="text-dark pt-5 pb-4", style="background-color: #FFE28C;">
    </footer>
    
  </body>
</html>